sudo: required
language: python
services:
    - docker
before_install:
    - sudo mkdir -p /data/log
    - pip install requests
script:
    - docker build -t judge-server:test .
    - docker pull registry.cn-hangzhou.aliyuncs.com/badcw-oj/oj-server
    - cp docker-compose.example.yml docker-compose.yml
    - docker-compose up -d
    - docker ps -a
    - sleep 5
    - python tests/tests.py
